name: Build & Test
on:
  push:
    branches:
      - develop
      - feature*
  pull_request:
    branches:
      - main
      - develop
      - feature*

concurrency:
  group: test-only
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/test-reusable.yml # Calls the reusable test workflow
    secrets: inherit